#!/bin/bash
set -e

# Usage: ./scripts/bump-version.sh [major|minor|patch|<explicit version>]
# Bumps version in the tracked app manifests and refreshes generated Android
# version metadata when the Android project has been initialized.

BUMP=${1:-patch}

current=$(grep '"version"' src-tauri/tauri.conf.json | head -1 | sed 's/.*"version": "\(.*\)".*/\1/')
IFS='.' read -r MAJ MIN PAT <<< "$current"

case "$BUMP" in
  major) MAJ=$((MAJ + 1)); MIN=0; PAT=0 ;;
  minor) MIN=$((MIN + 1)); PAT=0 ;;
  patch) PAT=$((PAT + 1)) ;;
  *)
    if [[ "$BUMP" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      MAJ=${BUMP%%.*}; rest=${BUMP#*.}; MIN=${rest%%.*}; PAT=${rest#*.}
    else
      echo "Invalid bump type: $BUMP"
      exit 1
    fi
    ;;
esac

new="${MAJ}.${MIN}.${PAT}"
echo "Bumping $current -> $new"

# tauri.conf.json — single root-level "version" key
sed -i.bak "s/\"version\": \"$current\"/\"version\": \"$new\"/" src-tauri/tauri.conf.json
rm -f src-tauri/tauri.conf.json.bak

# Cargo.toml — anchored on start-of-line to skip dependency versions
sed -i.bak "s/^version = \"$current\"/version = \"$new\"/" src-tauri/Cargo.toml
rm -f src-tauri/Cargo.toml.bak

# package.json — single root-level "version" key
sed -i.bak "s/\"version\": \"$current\"/\"version\": \"$new\"/" package.json
rm -f package.json.bak

# package-lock.json — root package metadata only
if [ -f package-lock.json ]; then
  node -e '
    const fs = require("fs");
    const file = "package-lock.json";
    const lock = JSON.parse(fs.readFileSync(file, "utf8"));
    lock.version = process.argv[1];
    if (lock.packages && lock.packages[""]) {
      lock.packages[""].version = process.argv[1];
    }
    fs.writeFileSync(file, JSON.stringify(lock, null, 2) + "\n");
  ' "$new"
fi

# Android's generated Gradle project reads versionName/versionCode from this
# ignored file. Keep it in sync before Android release builds.
ANDROID_PROPS=src-tauri/gen/android/app/tauri.properties
if [ -d "$(dirname "$ANDROID_PROPS")" ]; then
  android_code=$((MAJ * 1000000 + MIN * 1000 + PAT))
  cat > "$ANDROID_PROPS" <<EOF
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
tauri.android.versionName=$new
tauri.android.versionCode=$android_code
EOF
fi

# Refresh Cargo.lock entry so it doesn't lag
(cd src-tauri && cargo update -p common-stacks --offline >/dev/null 2>&1 || true)

echo "$new"
