#!/bin/bash
set -e

# Usage: ./scripts/release-android.sh [major|minor|patch|<version>|--no-bump] [--no-push]
#
# Android-only release flow:
#   1. bump tracked app versions and generated Android version metadata
#   2. build the signed arm64 release APK
#   3. upload the APK and merge platforms["android-arm64"] into latest.json
#   4. commit and push the version/script changes
#
# This intentionally does not install to a connected device and does not create
# a git tag, because Android can be released independently from desktop Tauri
# updater builds.

if [ -f .env.local ]; then
  set -a; . ./.env.local; set +a
fi

BUMP=patch
PUSH=1
for arg in "$@"; do
  case "$arg" in
    --no-bump) BUMP=--no-bump ;;
    --no-push) PUSH=0 ;;
    major|minor|patch) BUMP=$arg ;;
    *)
      if [[ "$arg" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        BUMP=$arg
      else
        echo "Unknown argument: $arg"
        echo "Usage: ./scripts/release-android.sh [major|minor|patch|<version>|--no-bump] [--no-push]"
        exit 1
      fi
      ;;
  esac
done

if ! git diff --quiet --exit-code -- \
  ':!src-tauri/tauri.conf.json' \
  ':!src-tauri/Cargo.toml' \
  ':!src-tauri/Cargo.lock' \
  ':!package.json' \
  ':!package-lock.json' \
  ':!scripts/upload-to-cloudflare.sh' \
  ':!scripts/bump-version.sh' \
  ':!scripts/release-android.sh'; then
  echo "Error: uncommitted changes outside release files."
  echo "Commit or stash them, then re-run."
  exit 1
fi

if [ "$BUMP" != "--no-bump" ]; then
  ./scripts/bump-version.sh "$BUMP" >/dev/null
fi

VERSION=$(grep '"version"' src-tauri/tauri.conf.json | head -1 | sed 's/.*"version": "\(.*\)".*/\1/')
ANDROID_PROPS=src-tauri/gen/android/app/tauri.properties
if [ ! -f "$ANDROID_PROPS" ]; then
  IFS='.' read -r MAJ MIN PAT <<< "$VERSION"
  android_code=$((MAJ * 1000000 + MIN * 1000 + PAT))
  cat > "$ANDROID_PROPS" <<EOF
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
tauri.android.versionName=$VERSION
tauri.android.versionCode=$android_code
EOF
fi
ANDROID_VERSION_NAME=$(sed -n 's/^tauri\.android\.versionName=//p' "$ANDROID_PROPS" 2>/dev/null | head -1)
ANDROID_VERSION_CODE=$(sed -n 's/^tauri\.android\.versionCode=//p' "$ANDROID_PROPS" 2>/dev/null | head -1)

echo "Building CommonStacks Android $ANDROID_VERSION_NAME ($ANDROID_VERSION_CODE)"

export ANDROID_HOME=${ANDROID_HOME:-"$HOME/Library/Android/sdk"}
export ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT:-"$ANDROID_HOME"}

bun install >/dev/null
env ANDROID_HOME="$ANDROID_HOME" ANDROID_SDK_ROOT="$ANDROID_SDK_ROOT" \
  npm run tauri -- android build --target aarch64 --apk --split-per-abi

APK=src-tauri/gen/android/app/build/outputs/apk/arm64/release/app-arm64-release.apk
if [ ! -f "$APK" ]; then
  echo "Error: Android release APK was not produced at $APK"
  exit 1
fi

BUILD_TOOLS=$(find "$ANDROID_SDK_ROOT/build-tools" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | sort | tail -1)
if [ -n "$BUILD_TOOLS" ] && [ -x "$BUILD_TOOLS/apksigner" ]; then
  "$BUILD_TOOLS/apksigner" verify --verbose "$APK"
fi
if [ -n "$BUILD_TOOLS" ] && [ -x "$BUILD_TOOLS/aapt" ]; then
  "$BUILD_TOOLS/aapt" dump badging "$APK" | sed -n '1p'
fi

./scripts/upload-to-cloudflare.sh

echo ""
echo "=== Published Android update ==="
curl -s https://releases.commonstacks.com/latest.json \
  | jq '.platforms["android-arm64"]'

if [ "$BUMP" != "--no-bump" ]; then
  git add package.json package-lock.json src-tauri/tauri.conf.json src-tauri/Cargo.toml src-tauri/Cargo.lock
fi
git add scripts/bump-version.sh scripts/release-android.sh scripts/upload-to-cloudflare.sh

if ! git diff --cached --quiet --exit-code; then
  git commit -m "Release Android v$ANDROID_VERSION_NAME"
  if [ "$PUSH" = "1" ]; then
    CURRENT_BRANCH=$(git branch --show-current)
    git push origin "$CURRENT_BRANCH"
  else
    echo "(skipped git push — --no-push was set)"
  fi
else
  echo "(no tracked changes to commit)"
fi

cat <<EOF

Done. Android v$ANDROID_VERSION_NAME ($ANDROID_VERSION_CODE) is published.
Do not install this APK manually when testing the in-app update path; open the
currently installed app and use Settings -> App updates -> Check.
EOF
